### ISSUE TITLE
extending a signed char to an int doesn't work, especially for -128

### ISSUE THREAD

**Issue by michaeladamkatz** [tringi/icomake#1]
Converting a 128x128 .png doesn't work because the width and height get extended to very large numbers, which the code rejects.

**Comment by michaeladamkatz** [comment]
I can't easily make a pull request on my employer's computer. The fix is to lines 131 and 132 of iconmake.cpp:

```
                        unsigned int width = ((unsigned char)header [16] << 24) | ((unsigned char)header [17] << 16) | ((unsigned char)header [18] << 8) | ((unsigned char)header [19] << 0);
                        unsigned int height = ((unsigned char)header [20] << 24) | ((unsigned char)header [21] << 16) | ((unsigned char)header [22] << 8) | ((unsigned char)header [23] << 0);

```

**Comment by tringi** [comment]
Oh, wow, nice catch! Thank you.
I checked all the places I use the tool, and I never tried it on PNG in 128 - 255 size range.

I decided to change the type of `header` array to `unsigned char`. That should do the trick too.

**Comment by michaeladamkatz** [comment]
Yeah, I wasn't sure if other places in the code relied on negative values in the header.

Thanks for the helpful tool. I couldn't find an online converter that would make a single .ico out of a set of files.

**Comment by tringi** [comment]
Yeah, same, that's why I wrote it.
Besides being able to embed PNGs smaller than 256×256.
Luckily the ICO format is so simple.
